# Generated by Django 3.1.4 on 2020-12-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_image_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
